language: python
python:
  - "3.10"
dist: jammy

env:
  global:
    - SAGE_SERVER=http://mirrors.xmission.com/sage/linux/64bit/
    - SAGE_BROKEN="['sage-8.1']"

matrix:
  include:
  - env: CACHE_NAME=latest DEPLOY_DOC_FROM_BRANCH=master DEPLOY_DOC_TO_REPOSITORY=koffie/mdsage
      DEPLOY_DOC_TO_DIRECTORY=doc/html SAGE_AGE=-1
addons:
  apt:
    packages:
    - gfortran
    - sagemath
    - texlive-latex-extra
script:
- ./.travis-test.sh
cache:
  directories:
  - $HOME/SageMath
  - $HOME/.cache/matplotlib
  timeout: 1000
before_cache:
- rm -Rf $HOME/SageMath/logs $HOME/SageMath/.BUILDSTART
after_success:
- ./.travis-deploy-doc.sh
before_script:
- openssl aes-256-cbc -K $encrypted_76f5f4384669_key -iv $encrypted_76f5f4384669_iv
  -in .travis_ci_gh_pages_deploy_key.enc -out .travis_ci_gh_pages_deploy_key -d || true
