language: python
sudo: required
matrix:
  include:
  - env: CACHE_NAME=latest DEPLOY_DOC_FROM_BRANCH=master DEPLOY_DOC_TO_REPOSITORY=koffie/mdsage
      DEPLOY_DOC_TO_DIRECTORY=doc/html SAGE_SERVER=http://mirrors.xmission.com/sage/linux/64bit/
      SAGE_AGE=0
  - env: CACHE_NAME=older SAGE_SERVER=http://mirrors.xmission.com/sage/linux/64bit/ SAGE_AGE=1
  # - env: CACHE_NAME=ubuntu-package SAGE_AGE=-1 # Uncomment to test against Ubuntu's packaged SageMath
  allow_failures:
  - env: CACHE_NAME=older SAGE_SERVER=http://mirrors.xmission.com/sage/linux/64bit/ SAGE_AGE=1
  # - env: CACHE_NAME=ubuntu-package SAGE_AGE=-1 # Uncomment to test against Ubuntu's packaged SageMath
addons:
   apt:
     packages:
      # On 8.0 with trusty, Fortran compiler is needed.
      # Otherwise, numpy cannot be imported.
      # Also, optional package installs in .travis-install.sh will trigger build of sage gcc.
      - gfortran
install:
- "./.travis-install.sh"
script:
- "./.travis-test.sh"
cache:
  directories:
  - "$HOME/SageMath"
  - "$HOME/.cache/matplotlib"
  timeout: 1000
before_cache:
- rm -Rf $HOME/SageMath/logs $HOME/SageMath/.BUILDSTART
after_success:
- "./.travis-deploy-doc.sh"
before_script:
