name: Run testsuite using pytest

on: [ workflow_dispatch, pull_request ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:9.6
      options: --user root

    steps:
      - name: Install git and make
        run: |
          sudo apt-get update
          sudo apt-get install git make -y
      - uses: actions/checkout@v2
      - name: make test
        run: |
          make test