name: Run testsuite using pytest

on: [ workflow_dispatch, pull_request ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:9.6
      options: --user root

    steps:
      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get install make -y
      - name: make test
        run: |
          make test
